POST http://localhost:3001/api/login/register
Content-Type: application/json

{
    "username": "Joel test 2",
    "password": "9090pass",
    "email": "joeltest@gmail.com",
    "tipo_user": "usuario"
}