POST http://localhost:3001/new/product
Content-Type: application/json

{
    "nombre": "Manejo de redes sociales",
    "precio": "20000",
    "descripcion": "1 semana de manejo de redes sociales, historias y publicaciones"
}

###
# Case 1: nombre not provided:
POST http://localhost:3001/new/product
Content-Type: application/json

{
    "nombre": "",
    "precio": "20000",
    "descripcion": "1 semana de manejo de redes sociales, historias y publicaciones"
}

###
# Case 2: precio not provided:
POST http://localhost:3001/new/product
Content-Type: application/json

{
    "nombre": "Manejo de redes sociales",
    "precio": "",
    "descripcion": "1 semana de manejo de redes sociales, historias y publicaciones"
}

###
# Case 3: descripcion not provided:
POST http://localhost:3001/new/product
Content-Type: application/json

{
    "nombre": "Manejo de redes sociales",
    "precio": "20000",
    "descripcion": ""
}