POST http://localhost:3001/api/campaign/new
Content-Type: application/json

{
    "nombre": "11 Campaña",
    "presupuesto": 400000
}

###
# Case 1: nombre not provided:
POST http://localhost:3001/api/campaign/new
Content-Type: application/json

{
    "nombre": "",
    "presupuesto": 300000
}

###
# Case 2: presupuesto not provided:
POST http://localhost:3001/api/campaign/new
Content-Type: application/json

{
    "nombre": "11 Campaña",
    "presupuesto": ""
}