POST http://localhost:3001/new/project
Content-Type: application/json

{
    "id_usuario": "46f5ebe3-a2ef-42c0-9917-79263f6887db",
    "nombre": "Rebranding de logo de empresa G"
}

###
# Case 1: the user provided does not exists on the database:
POST http://localhost:3001/new/project
Content-Type: application/json

{
    "id_usuario": 42,
    "nombre": "Rebranding de logo de empresa P"
}

###
# Case 2: user not provided:
POST http://localhost:3001/new/project
Content-Type: application/json

{
    "id_usuario": "",
    "nombre": "Rebranding de logo de empresa Y"
}

###
# Case 3: nombre not provided:
POST http://localhost:3001/new/project
Content-Type: application/json

{
    "id_usuario": "46f5ebe3-a2ef-42c0-9917-79263f6887db",
    "nombre": ""
}