POST http://localhost:3001/new/user
Content-Type: application/json

{
    "username": "Joel",
    "password": "9090pass",
    "email": "joel@gmail.com",
    "tipo_user": "usuario"
}

###
# --- Testing different cases: ---
# Case 1: username not provided:
POST http://localhost:3001/new/user
Content-Type: application/json

{
    "password": "9090pass",
    "email": "joel2@test.com",
    "tipo_user": "usuario"
}

###
# Case 2: username is too short:
POST http://localhost:3001/new/user
Content-Type: application/json

{
    "username": "",
    "password": "9090pass",
    "email": "joel2@test.com",
    "tipo_user": "usuario"
}

###
# Case 3: password too short:
POST http://localhost:3001/new/user
Content-Type: application/json

{
    "username": "Joel2",
    "password": "",
    "email": "joel2@test.com",
    "tipo_user": "usuario"
}

###
# Case 4: password not provided:
POST http://localhost:3001/new/user
Content-Type: application/json

{
    "username": "Joel2",
    "email": "joel2@test.com",
    "tipo_user": "usuario"
}

###
# Case 5: email too short:
POST http://localhost:3001/new/user
Content-Type: application/json

{
    "username": "Joel2",
    "password": "9090pass",
    "email": "",
    "tipo_user": "usuario"
}

###
# Case 6: email not provided:
POST http://localhost:3001/new/user
Content-Type: application/json

{
    "username": "Joel2",
    "password": "9090pass",
    "tipo_user": "usuario"
}

###
# Case 7: tipo_user not provided:
POST http://localhost:3001/new/user
Content-Type: application/json

{
    "username": "Joel2",
    "password": "9090pass",
    "email": "joel2@test.com",
    "tipo_user": ""
}